excluded:
    - Carthage
    - Pods

disabled_rules:
    - identifier_name
    - large_tuple
    - nesting
    - opening_brace
    - trailing_comma
    - type_name

opt_in_rules:
    - closure_end_indentation
    - closure_spacing
    - collection_alignment
    - conditional_returns_on_newline
    - contains_over_first_not_nil
    - convenience_type
    - empty_count
    - empty_string
    - explicit_init
    - fallthrough
    - fatal_error_message
    - first_where
    - force_unwrapping
    - function_default_parameter_at_end
    - identical_operands
    - implicitly_unwrapped_optional
    - let_var_whitespace
    - literal_expression_end_indentation
    - lower_acl_than_parent
    - modifier_order
    - nimble_operator
    - operator_usage_whitespace
    - overridden_super_call
    - pattern_matching_keywords
    - prefixed_toplevel_constant
    - private_action
    - private_outlet
    - prohibited_interface_builder
    - prohibited_super_call
    - redundant_nil_coalescing
    - redundant_type_annotation
    - required_enum_case
    - single_test_class
    - sorted_first_last
    - static_operator
    - strict_fileprivate
    - toggle_bool
    - unavailable_function
    - unneeded_parentheses_in_closure_argument
    - untyped_error_in_catch
    - unused_import
    - unused_private_declaration
    - vertical_parameter_alignment_on_call
    - yoda_condition

file_length: 1000
type_body_length: 500
function_body_length: 100

line_length:
    warning: 120
    error: 200
    ignores_comments: true
